### PR TITLE
Updated Composer.json to use latest version of symphony

### PR DESCRIPTION
**Pull request by tobya**
Without this update will not load for newer apps using lumen and symphony

### CODE REVIEW

**Comment by tobya** [comment]
@RealexITSO Any chance of getting this merged?

**Comment by victor-andreescu** [comment]
I agree with @tobya. In the current form the package is not compatible with Laravel 5.3. The upgrade is needed.

**Comment by rxp-developers** [comment]
Hi @tobya,

Apologies for not getting back to you. We're working on a new set of SDKs. However, I will review this Pull Request over the next few days to see if we can merge it without any issue. Thanks.

**Comment by tobya** [comment]
Thank you.

**Comment by shakaran** [comment]
@rxp-developers any progress with this? Thanks

**Comment by tobya** [comment]
> Hi @tobya,
> 
> Apologies for not getting back to you. We're working on a new set of SDKs. However, I will review this Pull Request over the next few days to see if we can merge it without any issue. Thanks.

Hello @rxp-developers could you let me know where th enew SDKs are?

**Comment by shakaran** [comment]
@tobya As far I know:

https://github.com/globalpayments/php-sdk

And for Spain with "La Caixa" (addon Payments)

https://github.com/AddonPayments/php-sdk

@rxp-developers I think that should be a good idea update in the README.md of this repository instead only in description

**Comment by tobya** [comment]
Thanks - I really cant see how it would hurt @rxp-developers  to update the composer.json file .  I really dont want to have to reimplement the booking engine because of this.

**Pull request closed without merging**
